---
# tasks file for nginx
- name: 4. install nginx
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nginx
    - python2-httplib2

- name: 5. setup loadbalancer for demo app
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
    backup: yes
  notify: restart nginx

- name: 5. start nginx service
  service:
    name: nginx
    state: started
    enabled: yes


