---
- hosts: lbstack
  become: true 
 
  tasks:
    - set_fact:
        real_ansible_host: "{{ ansible_host }}"

    - name: restart hosts
      shell: sleep 3 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: wait for hosts to go down
      local_action:
        wait_for host={{ real_ansible_host }}
        port=22 state=absent delay=5 timeout=120
      become: false

    - name: wait for hosts to come back up
      local_action:
        wait_for host={{ real_ansible_host }}
        port=22 state=started delay=30 timeout=120
      become: false
