---
#bring down stack
- hosts: loadbalancer
  become: true
 
  tasks: 
    - name: bring down nginx loadbalancer service
      service: 
        name: nginx
        state: stopped
    
    - name: wait for traffic on nginx to drain
      wait_for: port=80 state=drained 

- hosts: webserver 
  become: true

  tasks:
    - name: bring down httpd service
      service:
        name: httpd 
        state: stopped

    - name: wait for httpd to close the port 
      wait_for: port=80 state=stopped

#restart stack
- hosts: database 
  become: true

  tasks:
    - name: restart mariadb database service 
      service:
        name: mariadb 
        state: restarted 

    - name: wait for mariadb to listen for connection 
      wait_for: port=3306 delay=3 state=started

#bring up stack
- hosts: webserver
  become: true

  tasks:
    - name: bring up httpd service
      service:
        name: httpd
        state: started

    - name: wait for httpd to listen for traffic 
      wait_for: port=80 delay=3 state=started

- hosts: loadbalancer
  become: true

  tasks:
    - name: bring up nginx loadbalancer service
      service:
        name: nginx
        state: started

    - name: wait for nginx to listen for traffic 
      wait_for: port=80 delay=3 state=started

